theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "wlan0"
ssid = true
signal_strength = true
ip = true
speed_up = false
graph_up = false
interval = 5
use_bits = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 8.0
alert = 5.0

[[block]]
block = "disk_space"
path = "/home"
alias = "home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pulseaudio-ctl mute"

[[block]]
block = "sound"
name = "@DEFAULT_SOURCE@"
driver = "pulseaudio"
on_click = "pulseaudio-ctl mute-input"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}% {time}"

[[block]]
block = "pacman"
interval = 3600
format = "{count} updates available"
format_singular = "{count} update available"
format_up_to_date = "system up to date"
